# Flutter build

trigger:
- develop
jobs:
  # - job: Android

  #   pool:
  #     vmImage: 'macOS-latest'

  #   steps:
  #   - task: FlutterInstall@0
  #     inputs:
  #       channel: 'stable'
  #       version: 'latest'
    
  #   - task: FlutterBuild@0
  #     inputs:
  #       target: 'apk'
  #       projectDirectory: '.'
  #       buildFlavour: 'dev'
  #       buildNumber: 
  #       entryPoint: 'lib/main_dev.dart'

  - job: iOS

    pool:
      vmImage: 'macOS-latest'

    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    - task: Xcode@5
      inputs:
        actions: 'build'
        configuration: 'dev'
        packageApp: false
    - task: FlutterBuild@0
      inputs:
        target: 'ios'
        projectDirectory: '.'
        buildFlavour: 'dev'
        buildNumber: 
        entryPoint: 'lib/main_dev.dart'
